# Generated by Django 3.1.6 on 2021-02-08 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.IntegerField()),
                ('name', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('rooms', models.IntegerField()),
                ('room_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('regNo', models.CharField(max_length=12)),
                ('sex', models.CharField(max_length=1)),
                ('date_payed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
