# Generated by Django 3.1.6 on 2021-02-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210217_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='hostel',
            new_name='hostelNum',
        ),
    ]
