# Generated by Django 3.1.6 on 2021-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210217_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='room_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='hostelNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
