# Generated by Django 3.1.6 on 2021-02-17 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210217_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('regNo', models.CharField(max_length=12)),
                ('sex', models.TextField(default='')),
                ('hostelNum', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('date_payed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
