# Generated by Django 3.1.6 on 2021-02-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210217_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='hostelNum',
            new_name='hostel',
        ),
    ]
