# Generated by Django 3.1.6 on 2021-02-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210217_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stud',
            new_name='Student',
        ),
    ]
