# Generated by Django 3.1.6 on 2021-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210308_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regNo',
            field=models.CharField(max_length=24),
        ),
    ]
