# Generated by Django 3.1.6 on 2021-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210308_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='roomBaseSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='allocated',
            field=models.IntegerField(default=0),
        ),
    ]
