# Generated by Django 3.1.6 on 2021-03-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210316_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
